### ISSUE TITLE
Error: Can't resolve './pkg/rust_3d_demo'

### ISSUE THREAD

**Issue by harlantwood** [dmilford/rust-3d-demo#1]
Hello, with either `npm run dev` or `npm run build` I get:

```
ERROR in ./index.js
Module not found: Error: Can't resolve './pkg/rust_3d_demo' in '/[...]/rust-3d-demo'
 @ ./index.js 1:13-41
```

Note: it looks like `pkg` is gitignore'd, so maybe there is missing source?

Thanks @dmilford for great videos btw 😄

**Comment by dmilford** [comment]
In the README file in the main folder of the project, there are some instructions to initialize the project.  Do those steps and let me know if you still have an issue.  I've pasted the initialization instructions below for your convenience.

# Initialization
    In your command line terminal, type...
        rustup target add wasm32-unknown-unknown
            - This will make sure you have wasm as a target for Rust
        cargo build
            - This will download all your Rust crates and make sure your Rust can build.  May take a minute.
        npm install
            - This will download all you node packages.  May take a minute.

**Comment by guillaume-michel** [comment]
To solve the issue, I had to install wasm-pack following the instructions at:
https://rustwasm.github.io/wasm-pack/installer/
